SET DEFINE OFF;

BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables WHERE table_name IN ('COMPONENT_IMAGES', 'ISSUE_RECORDS', 'LAB_COMPONENTS', 'BRANCH_LABS', 'ACADEMIC_BRANCHES', 'SYSTEM_USERS')) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

CREATE TABLE system_users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'ADMIN' NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO system_users (username, password_hash, role, is_active)
VALUES ('admin', 'admin123', 'ADMIN', 1);

CREATE TABLE academic_branches (
    branch_code VARCHAR2(50) PRIMARY KEY,
    branch_name VARCHAR2(100) NOT NULL,
    branch_password VARCHAR2(255),
    recovery_email VARCHAR2(100),
    recovery_phone VARCHAR2(20)
);

CREATE TABLE branch_labs (
    lab_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    branch_code VARCHAR2(50) REFERENCES academic_branches(branch_code) ON DELETE CASCADE,
    lab_name VARCHAR2(100) NOT NULL,
    CONSTRAINT unq_branch_lab UNIQUE (branch_code, lab_name)
);

CREATE TABLE lab_components (
    comp_id VARCHAR2(50) NOT NULL,
    comp_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    specifications VARCHAR2(200),
    branch_code VARCHAR2(50) REFERENCES academic_branches(branch_code) ON DELETE CASCADE,
    total_qty NUMBER(6) NOT NULL,
    issued_qty NUMBER(6) DEFAULT 0 NOT NULL,
    available_qty NUMBER(6) NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_comp PRIMARY KEY (comp_id, branch_code)
);

CREATE TABLE component_images (
    image_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    comp_id VARCHAR2(50) NOT NULL,
    branch_code VARCHAR2(50) NOT NULL,
    image_data BLOB NOT NULL
);

CREATE TABLE issue_records (
    issue_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    enrollment_no VARCHAR2(50) NOT NULL,
    student_name VARCHAR2(100) NOT NULL,
    student_branch VARCHAR2(50) NOT NULL,
    student_mobile VARCHAR2(15) NOT NULL,
    comp_id VARCHAR2(50) NOT NULL,
    branch_code VARCHAR2(50) NOT NULL,
    issue_date DATE DEFAULT SYSDATE NOT NULL,
    due_date DATE DEFAULT SYSDATE + 7,
    issue_qty NUMBER(6) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,
    return_date DATE NULL,
    returned_qty NUMBER(6) DEFAULT 0,
    issued_by VARCHAR2(50) NOT NULL,
    student_email VARCHAR2(100),
    return_condition VARCHAR2(50),
    penalty_fee NUMBER(10,2) DEFAULT 0
);

COMMIT;